### PR TITLE
T/96 Tree Model refactor

### PR DESCRIPTION
**Pull request by scofalik**
This pull request combines changes done for several issues: #98 #96 #91 #73 and #66

### CODE REVIEW

**Comment by scofalik** [comment]
#84 joined the party.

**Comment by scofalik** [comment]
I will also include #67 here and then it will be ready for review.

**Comment by scofalik** [comment]
This is ready for review. Keep in mind that these refactor changes are conflicting with changes in #106 so I think it will be better to first merge #106 with master and only then this one. We should do it ASAP, though.

**Comment by scofalik** [comment]
I've also included #104 as it is very tiny.

**Comment by scofalik** [comment]
Added #107

**Comment by pjasiun** [comment]
I checked and merged these changes, because they are blocking all other changes in the ~~document~~ tree model. Most changes are fine, but https://github.com/ckeditor/ckeditor5-core/issues/84 needs more tests and fixes. It can be done in a separate PR.

**Pull request merged**
