### PR TITLE
Introduced EditorUI#update event

### LINKED ISSUE #130: Introduce EditorUI#update event
Now we use `view#render` event to attach and reposition floating UI stuff. The problem is that rendered layout should not be the only reposition trigger. We are going to introduce `ViewDocument#layoutChanged` event https://github.com/ckeditor/ckeditor5-engine/issues/1445 so we will have another trigger soon. Besides, we should make it possible to trigger UI refresh manually without touching the engine part.

We decided to introduced one `EditorUI#update` event. This event should be fired every time when editor UI should be refreshed (after all document layout changes). All UI part of the plugins should listen to this event instead of `view#render`.

Related stuff:
- https://github.com/ckeditor/ckeditor5-engine/issues/1445
- https://github.com/ckeditor/ckeditor5-image/pull/210

### LINKED ISSUE #2890: Introduce EditorUI#update event
Now we use `view#render` event to attach and reposition floating UI stuff. The problem is that rendered layout should not be the only reposition trigger. We are going to introduce `ViewDocument#layoutChanged` event https://github.com/ckeditor/ckeditor5-engine/issues/1445 so we will have another trigger soon. Besides, we should make it possible to trigger UI refresh manually without touching the engine part.

We decided to introduced one `EditorUI#update` event. This event should be fired every time when editor UI should be refreshed (after all document layout changes). All UI part of the plugins should listen to this event instead of `view#render`.

Related stuff:
- https://github.com/ckeditor/ckeditor5-engine/issues/1445
- https://github.com/ckeditor/ckeditor5-image/pull/210

### PR DESCRIPTION
**Pull request by oskarwrobel**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Introduced `EditorUI#update` event. Closes ckeditor/ckeditor5#2890.

BREAKING CHANGE: `EditorUI` is not an interface anymore. It is a class now.

---

## CI
- https://github.com/ckeditor/ckeditor5/tree/t/ckeditor5-core/130

### Editors
- https://github.com/ckeditor/ckeditor5-editor-classic/pull/74
- https://github.com/ckeditor/ckeditor5-editor-inline/pull/40
- https://github.com/ckeditor/ckeditor5-editor-balloon/pull/21
- https://github.com/ckeditor/ckeditor5-editor-decoupled/pull/16
### Plugins
- https://github.com/ckeditor/ckeditor5-link/pull/197
- https://github.com/ckeditor/ckeditor5-table/pull/78
- https://github.com/ckeditor/ckeditor5-ui/pull/416
- https://github.com/ckeditor/ckeditor5-image/pull/215

### CODE REVIEW

**Review by oleq — APPROVED** [review]

**Comment by oleq** [comment]
@Mgsy Can you check out the constellation? The changes affect almost every feature and there could be serious regressions.

**Comment by Mgsy** [comment]
The link balloon doesn't close after leaving the link.

bug_cke5

Browser: All browsers

**Comment by Mgsy** [comment]
The link balloon doesn't update its position.

bug_cke5

Browser: All browsers

**Comment by Mgsy** [comment]
The link balloon shows up in incorrect position after applying a link to a caption.

bug_cke5

Browser: All browsers

**Comment by Mgsy** [comment]
The link balloon shows up in incorrect position after applying a link to the whole content.

bug_cke5

Browser: All browsers

**Comment by oskarwrobel** [comment]
I can't reproduce anything.

jun-28-2018 10-23-38

jun-28-2018 10-25-26

**Comment by Mgsy** [comment]
The link balloon 'jumps' after applying the link:

bug_cke5

After changing throttling time from `50ms` to `10ms` [in this line](https://github.com/ckeditor/ckeditor5-core/blob/t/130/src/editor/editorui.js#L70), everything works fine.

**Comment by oskarwrobel** [comment]
> The link balloon 'jumps' after applying the link:

Done.

**Review by Mgsy — APPROVED** [review]
LGTM.

**Pull request merged**
