### PR TITLE
Added Mathtype and Wproofreader manual tests

### LINKED ISSUE #2027: Manual tests for Wproofreader and Mathtype
## Is this a bug report or feature request? (choose one)

Task

## 💻 Version of CKEditor

There are tests for [Mathtype](https://github.com/ckeditor/ckeditor5-core/tree/t/mathtype) and [Wproofreader](https://github.com/ckeditor/ckeditor5-core/tree/t/wproofreader) on temp branches. These tests should be added to the master branch.

### PR DESCRIPTION
**Pull request by mlewand**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Tests: Added Mathtype and Wproofreader manual tests. Closes ckeditor/ckeditor5#2027.

---

### Additional information

Note that Mathtype have few icons that do not use a sprite. This causes a serries of network errors when opening Mathtype plugin for the first time:

```
http://localhost:8125/ckeditor5-core/tests/manual/icons/general/close_icon.png 404
http://localhost:8125/ckeditor5-core/tests/manual/icons/general/mins_icon.png 404
http://localhost:8125/ckeditor5-core/tests/manual/icons/general/fulls_icon.png 404
http://localhost:8125/ckeditor5-core/tests/manual/icons/general/min_icon.png 404
```

We have three options of fixing it: 

* issue should be fixed in the mathtype plugin itself as anyone importing this plugin will face same issue,
* add a `file-loader` to our manual test webpack configuration,
* simply place these icons in the file system, in `icons` directory next to manual test.

I find the first more sustainable.

### CODE REVIEW

**Comment by mlewand** [comment]
@Mgsy can I ask you to click out the PR before we proceed with the review? I did some major changes in couple of places, especially reduced CSP settings.

**Review by Mgsy — APPROVED** [review]
LGTM.

**Comment by mlewand** [comment]
@pomek PTAL 🙂

**Comment by pomek** [comment]
Note: after resolving https://github.com/ckeditor/ckeditor5/issues/2054, those tests should be moved to ckeditor/ckeditor5 repo.

**Comment by pomek** [comment]
Let's say, it works. When we will be moving those tests to the proper repository, we need to mention:
- we are aware of 404 errors in Mathtype tests,
- how to test Wproofreader (custom domain)

**Pull request merged**
