### PR TITLE
Test: Fix editor destroy tests when waiting for full initialization p…

### LINKED ISSUE #6138: Useless tests in ckeditor5-core
## 📝 Provide detailed reproduction steps (if any)

This test: https://github.com/ckeditor/ckeditor5-core/blob/8a88cb52c122fd2952f88f8773a03808f32d6037/tests/editor/editor.js#L353-L366

```js
it( 'should wait for the full init before destroying', done => {
	const spy = sinon.spy();
	const editor = new TestEditor();

	editor.on( 'destroy', () => {
		done();
	} );

	editor.destroy();

	sinon.assert.notCalled( spy );

	editor.fire( 'ready' );
} );
```
does not test anything

### ✔️ Expected result

The test shold test something.

### ❌ Actual result

:thinking: 

## 📃 Other details

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Test: Fix editor destroy tests when waiting for a full initialization process. Closes ckeditor/ckeditor5#6138.

---

### Additional information

*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

### CODE REVIEW

**Comment by Reinmar** [comment]
I don't get this change :D

**Comment by jodator** [comment]
Previously the test wasn't doing any assertion.

The whole test:

```js
it( 'should wait for the full init before destroying', done => {
	const spy = sinon.spy();
	const editor = new TestEditor();

	editor.on( 'destroy', spy );

	editor.on( 'destroy', () => {
		sinon.assert.calledOnce( spy );

		done();
	} );

	editor.destroy();

	sinon.assert.notCalled( spy );

	editor.fire( 'ready' );
} );
```

What it does it creates an editor's instance and immediately destroy it. The destroy Promise is not resolved until some internal thingy fires the 'ready' event. The 'destroy' event is fired when that Promise is resolved.

This tests checks if calling destroys before "ready" (initialization process finished) does not blow things up. So the spy cannot be called before 'ready' event.

I think that was the fastest way of making this test test something rather than just running. I see there couple of problems but that would be a bigger story.

**Comment by Reinmar** [comment]
I went with 033f500.

**Comment by Reinmar** [comment]
I went with 033f500.

**Pull request closed without merging**
