### PR TITLE
i/6169: Enhance Image and Block Quote plugins icons

### PR DESCRIPTION
**Pull request by panr**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Enhanced Image and Block Quote plugin icon. See ckeditor/ckeditor5#6168

--
Related to: ckeditor/ckeditor5#6169
Master PR: ckeditor/ckeditor5-media-embed#95

### CODE REVIEW

**Review by oleq — COMMENTED** [review]
Why was the "sun" scaled down?

image

**Review by oleq — CHANGES_REQUESTED** [review]
Why was the icon horizontally squashed in this PR? What does it have to do with the vertical re-alignment?

image

**Comment by panr** [comment]
Oh... I edited it in Figma (not Sketch) and something went wrong here :-/ Losing a grid is a crime... Sorry about that :-(

**Comment by panr** [comment]
I'm closing the PR as I mentioned here https://github.com/ckeditor/ckeditor5/issues/6168

**Pull request closed without merging**
