### PR TITLE
T/112 c: TreeView classes structure

### PR DESCRIPTION
**Pull request by pjasiun**
Fixes: #112.

### CODE REVIEW

**Comment by Reinmar** [comment]
Second part of this test is too complicate to validate: http://tests.ckeditor.dev:1030/dist/amd/tests/core/treeview/manual/mutationobserver

**Comment by pjasiun** [comment]
That is true. You can remove it.

**Comment by Reinmar** [comment]
The second part?

**Comment by pjasiun** [comment]
Yep, the first part I believe is useful.

**Comment by Reinmar** [comment]
We're getting super close to a functional editor :) Kudos!

**Pull request merged**
